apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-stock-bot-node-deployment
  labels:
    app: telegram-stock-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-stock-bot
  template:
    metadata:
      labels:
        app: telegram-stock-bot
    spec:
      containers:
        - name: telegram-stock-bot-node
          image: gcr.io/PROJECT_ID/IMAGE:GITHUB_SHA
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: defaultconfig
            - secretRef:
                name: telegram-alphavantage-secret