apiVersion: "v1"
kind: "Service"
metadata:
  name: "telegram-stock-bot-service"
  namespace: "default"
  labels:
    app: "telegram-stock-bot"
spec:
  ports:
    - protocol: "TCP"
      port: 8080
  selector:
    app: "telegram-stock-bot"
  type: "LoadBalancer"