name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker build image of nodejs
      run: |
        docker build -t telegramstockbot .
    - name: Docker push
      run: |
        docker push telegramstockbot
